name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # oder deine gewünschte Version

      - name: Install dependencies
        run: npm install --save-dev

      - name: Run deploy script
        run: npm run deploy
