name: Daily Data Update and Deploy

on:
  schedule:
    - cron: "22 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  USERAGENT: https://github.com/LuisErhardt/delay-catcher
  TZ: Europe/Berlin

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show runner time
        run: |
          echo "Time of runner:"
          date

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run delay-catcher
        run: npx delay-catcher 8000207 public/data

      - name: Generate file list
        run: node generateFileList.cjs

      - name: Commit and push changes
        run: |
          git config user.name "Luis Erhardt"
          git config user.email "LuisErhardt@users.noreply.github.com"
          git add -A
          git commit -m "data" || echo "No changes to commit"
          git push

      - name: Build website
        run: npm run build

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist


  deploy:
    needs: update-data
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          
